export const MAX_IMAGE_SIZE = 5_242_880; // ~5 MB
export const MAX_GIF_SIZE = 15_728_640; // ~15 MB
export const MAX_VIDEO_SIZE = 536_870_912; // ~530 MB

export const APIs = {
  CreateTweet: ['7TKRKCPuAGsmYde0CudbVg', 'CreateTweet'],
};

export const defaultVariables = {
  count: 1000,
  withSafetyModeUserFields: true,
  includePromotedContent: true,
  withQuickPromoteEligibilityTweetFields: true,
  withVoice: true,
  withV2Timeline: true,
  withDownvotePerspective: false,
  withBirdwatchNotes: true,
  withCommunity: true,
  withSuperFollowsUserFields: true,
  withReactionsMetadata: false,
  withReactionsPerspective: false,
  withSuperFollowsTweetFields: true,
  isMetatagsQuery: false,
  withReplays: true,
  withClientEventToken: false,
  withAttachments: true,
  withConversationQueryHighlights: true,
  withMessageQueryHighlights: true,
  withMessages: true,
};

export const defaultFeatures = {
  c9s_tweet_anatomy_moderator_badge_enabled: true,
  responsive_web_home_pinned_timelines_enabled: true,

  blue_business_profile_image_shape_enabled: true,
  creator_subscriptions_tweet_preview_api_enabled: true,
  freedom_of_speech_not_reach_fetch_enabled: true,
  graphql_is_translatable_rweb_tweet_is_translatable_enabled: true,
  graphql_timeline_v2_bookmark_timeline: true,
  hidden_profile_likes_enabled: true,
  highlights_tweets_tab_ui_enabled: true,
  interactive_text_enabled: true,
  longform_notetweets_consumption_enabled: true,
  longform_notetweets_inline_media_enabled: true,
  longform_notetweets_rich_text_read_enabled: true,
  longform_notetweets_richtext_consumption_enabled: true,
  profile_foundations_tweet_stats_enabled: true,
  profile_foundations_tweet_stats_tweet_frequency: true,
  responsive_web_birdwatch_note_limit_enabled: true,
  responsive_web_edit_tweet_api_enabled: true,
  responsive_web_enhance_cards_enabled: false,
  responsive_web_graphql_exclude_directive_enabled: true,
  responsive_web_graphql_skip_user_profile_image_extensions_enabled: false,
  responsive_web_graphql_timeline_navigation_enabled: true,
  responsive_web_media_download_video_enabled: false,
  responsive_web_text_conversations_enabled: false,
  responsive_web_twitter_article_data_v2_enabled: true,
  responsive_web_twitter_article_tweet_consumption_enabled: false,
  responsive_web_twitter_blue_verified_badge_is_enabled: true,
  rweb_lists_timeline_redesign_enabled: true,
  spaces_2022_h2_clipping: true,
  spaces_2022_h2_spaces_communities: true,
  standardized_nudges_misinfo: true,
  subscriptions_verification_info_verified_since_enabled: true,
  tweet_awards_web_tipping_enabled: false,
  tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled: true,
  tweetypie_unmention_optimization_enabled: true,
  verified_phone_label_enabled: false,
  vibe_api_enabled: true,
  view_counts_everywhere_api_enabled: true,
};

export const trendingParams = {
  include_profile_interstitial_type: 1,
  include_blocking: 1,
  include_blocked_by: 1,
  include_followed_by: 1,
  include_want_retweets: 1,
  include_mute_edge: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_verified_type: 1,
  skip_status: 1,
  cards_platform: 'Web-12',
  include_cards: 1,
  include_ext_alt_text: true,
  include_ext_limited_action_results: false,
  include_quote_count: true,
  include_reply_count: 1,
  tweet_mode: 'extended',
  include_ext_views: true,
  include_entities: true,
  include_user_entities: true,
  include_ext_media_color: true,
  include_ext_media_availability: true,
  include_ext_sensitive_media_warning: true,
  include_ext_trusted_friends_metadata: true,
  send_error_codes: true,
  simple_quoted_tweet: true,
  count: 1000,
  requestContext: 'launch',
  include_page_configuration: true,
  initial_tab_id: 'trending',
  entity_tokens: false,
  ext: 'mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,enrichments,superFollowMetadata,unmentionInfo,editControl,vibe',
};

export const accountSettings = {
  address_book_live_sync_enabled: false,
  allow_ads_personalization: false,
  allow_authenticated_periscope_requests: true,
  allow_dm_groups_from: 'following',
  allow_dms_from: 'following', // all
  allow_location_history_personalization: false,
  allow_logged_out_device_personalization: false,
  allow_media_tagging: 'none', // all, following
  allow_sharing_data_for_third_party_personalization: false,
  alt_text_compose_enabled: null,
  always_use_https: true,
  autoplay_disabled: false,
  country_code: 'us',
  discoverable_by_email: false,
  discoverable_by_mobile_phone: false,
  display_sensitive_media: true,
  dm_quality_filter: 'enabled', // disabled
  dm_receipt_setting: 'all_disabled', // all_enabled
  geo_enabled: false,
  include_alt_text_compose: true,
  include_mention_filter: true,
  include_nsfw_admin_flag: true,
  include_nsfw_user_flag: true,
  include_ranked_timeline: true,
  language: 'en',
  mention_filter: 'unfiltered',
  nsfw_admin: false,
  nsfw_user: false,
  personalized_trends: true,
  protected: false,
  ranked_timeline_eligible: null,
  ranked_timeline_setting: null,
  require_password_login: false,
  requires_login_verification: false,
  settings_metadata: {},
  sleep_time: {
    enabled: false,
    end_time: null,
    start_time: null,
  },
  translator_type: 'none',
  universal_quality_filtering_enabled: 'enabled',
  use_cookie_personalization: false,
  // todo: not yet implemented - requires additional steps
  // // 'allow_contributor_request': 'all',
  // 'protect_password_reset': false,
};

export const followerNotificationSettings = {
  cursor: -1,
  include_profile_interstitial_type: 1,
  include_blocking: 1,
  include_blocked_by: 1,
  include_followed_by: 1,
  include_want_retweets: 1,
  include_mute_edge: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_verified_type: 1,
  skip_status: 1,
};

export const followSettings = {
  include_profile_interstitial_type: 1,
  include_blocking: 1,
  include_blocked_by: 1,
  include_followed_by: 1,
  include_want_retweets: 1,
  include_mute_edge: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_verified_type: 1,
  skip_status: 1,
};

export const accountSearchSettings = {
  optInFiltering: true, // filter out nsfw content
  optInBlocking: true, // filter out blocked accounts
};

export const searchConfig = {
  include_profile_interstitial_type: 1,
  include_blocking: 1,
  include_blocked_by: 1,
  include_followed_by: 1,
  include_want_retweets: 1,
  include_mute_edge: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_verified_type: 1,
  skip_status: 1,
  cards_platform: 'Web-12',
  include_cards: 1,
  include_ext_alt_text: true,
  include_ext_limited_action_results: false,
  include_quote_count: true,
  include_reply_count: 1,
  tweet_mode: 'extended',
  include_ext_collab_control: true,
  include_ext_views: true,
  include_entities: true,
  include_user_entities: true,
  include_ext_media_color: true,
  include_ext_media_availability: true,
  include_ext_sensitive_media_warning: true,
  include_ext_trusted_friends_metadata: true,
  send_error_codes: true,
  simple_quoted_tweet: true,
  query_source: 'typed_query',
  count: 1000,
  q: '',
  requestContext: 'launch',
  pc: 1,
  spelling_corrections: 1,
  include_ext_edit_control: true,
  ext: 'mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,enrichments,superFollowMetadata,unmentionInfo,editControl,collab_control,vibe',
};

export const dmParams = {
  context: 'FETCH_DM_CONVERSATION',
  include_profile_interstitial_type: 1,
  include_blocking: 1,
  include_blocked_by: 1,
  include_followed_by: 1,
  include_want_retweets: 1,
  include_mute_edge: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_verified_type: 1,
  include_ext_profile_image_shape: 1,
  skip_status: 1,
  dm_secret_conversations_enabled: false,
  krs_registration_enabled: true,
  cards_platform: 'Web-12',
  include_cards: 1,
  include_ext_alt_text: true,
  include_ext_limited_action_results: false,
  include_quote_count: true,
  include_reply_count: 1,
  tweet_mode: 'extended',
  include_ext_views: true,
  dm_users: false,
  include_groups: true,
  include_inbox_timelines: true,
  include_ext_media_color: true,
  supports_reactions: true,
  include_conversation_info: true,
  ext: 'mediaColor,altText,mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,superFollowMetadata,unmentionInfo,editControl',
};

export const liveNotificationParams = {
  cards_platform: 'Web-12',
  count: 50, // max value
  ext: 'mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,superFollowMetadata,unmentionInfo,editControl',
  include_blocked_by: 1,
  include_blocking: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_cards: 1,
  include_entities: true,
  include_ext_alt_text: true,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_limited_action_results: true,
  include_ext_media_availability: true,
  include_ext_media_color: true,
  include_ext_profile_image_shape: 1,
  include_ext_sensitive_media_warning: true,
  include_ext_trusted_friends_metadata: true,
  include_ext_verified_type: 1,
  include_ext_views: true,
  include_followed_by: 1,
  include_mute_edge: 1,
  include_profile_interstitial_type: 1,
  include_quote_count: true,
  include_reply_count: 1,
  include_user_entities: true,
  include_want_retweets: 1,
  send_error_codes: true,
  simple_quoted_tweet: true,
  skip_status: 1,
  tweet_mode: 'extended',
};

export const recommendationsParams = {
  include_profile_interstitial_type: 1,
  include_blocking: 1,
  include_blocked_by: 1,
  include_followed_by: 1,
  include_want_retweets: 1,
  include_mute_edge: 1,
  include_can_dm: 1,
  include_can_media_tag: 1,
  include_ext_has_nft_avatar: 1,
  include_ext_is_blue_verified: 1,
  include_ext_verified_type: 1,
  include_ext_profile_image_shape: 1,
  skip_status: 1,
  pc: true,
  display_location: 'profile_accounts_sidebar',
  limit: 100,
  ext: 'mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,superFollowMetadata,unmentionInfo,editControl',
};
